name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  push-to-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create new develop from main
      run: |
        git config --global user.name ${{ secrets.MY_GITHUB_NAME }}
        git config --global user.email ${{ secrets.MY_GITHUB_EMAIL }}
        git checkout main
        git pull
        git branch -d develop
        git checkout -b develop

    - name: Run build_readme.sh
      run: bash ./.scripts/build_readme.sh

    - name: Commit and Push README.md and index.html
      uses: EndBug/add-and-commit@v9
      with:
        author_name: ${{ secrets.MY_GITHUB_NAME }}
        author_email: ${{ secrets.MY_GITHUB_EMAIL }}
        message: "[GitHub Actions] Automated update of README.md and index.html files."

    - name: Push to release branch
      run: |
        git checkout -b release
        git push --force origin release
