name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  push-to-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build_readme.sh
      run: bash ./.scripts/build_readme.sh

    - name: Commit and Push README.md
      uses: EndBug/add-and-commit@v9
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ secrets.MY_GITHUB_EMAIL }}
        message: "[GitHub Actions] Automated update of README.md file."

    - name: Push to release branch
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ secrets.MY_GITHUB_EMAIL }}
        git checkout -b release
        git push --force origin release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: release
        cname: ${{ secrets.MY_PAGE_DOMAIN }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
      
   