name: Every push to main, build content, push to release for deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  push-to-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Update develop branch
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b develop
          git push --force origin develop
          git checkout main
      - name: Run build_readme.sh
        run: bash ./.scripts/build_readme.sh
      - name: Commit and Push README.md
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated update of README.md file."
      - name: Create and push to release branch
        run: |
          git checkout -b release
          git push --force origin release
